### PR TITLE
Disown preexec'd process if possible

### LINKED ISSUE #6: fasd process always in background
When this plugin is installed it hooks to `fish_preexec` and keeps backgrounding a `fasd` process.

I found that this is the offending line:
https://github.com/oh-my-fish/plugin-fasd/blob/master/init.fish#L5

Removing the backgrounding ampensand (`&`) should fix the issue.

### PR DESCRIPTION
**Pull request by elmisback**
Fixes #6 on fish 2.6.0 only as per [this suggestion](https://github.com/oh-my-fish/plugin-fasd/issues/6#issuecomment-310719965)

### CODE REVIEW

**Comment by mtbrock** [comment]
Hey why has this not been merged?

**Comment by elmisback** [comment]
This repo hasn't seen many updates recently, and @simnalamburt is pretty busy. This PR might have slipped through the cracks.

**Comment by mtbrock** [comment]
Yeah that makes sense. It's not a big deal really but @simnalamburt could at least give write/admin permission to someone else if he is unable to maintain this repo. I'd be glad to help maintain and I'm sure there are others who are willing as well.

**Comment by elmisback** [comment]
I'd also be willing to help out. If we don't hear from @simnalamburt in the next day or two (or sooner), I'll try contacting someone from oh-my-fish about getting write permission for this repo.

**Comment by simnalamburt** [comment]
@elmisback @mtbrock Sorry, I just reviewed and merged the PR.

I'm not the owner or admin of this repository. So I cannot grant write access of this repository to someone else. Yes I did create the plugin-fasd but I transfered this repository to the oh-my-fish for public interest, and I gave up my admin access to this repo. Current owner of this repository is @bobthecow so maybe he/she can help you out.

By the way, since fasd itself is not being activaly developed since 2015, I stopped using fasd resulting this repository to be staled.

**Comment by bobthecow** [comment]
Sorry, I didn't see this issue. I'm happy to add additional contributors to this repo as needed, especially since it's not being actively developed. @elmisback, are you up for this? @simnalamburt, do you mind?

**Comment by elmisback** [comment]
Yes, I'd be happy to help out.

**Comment by simnalamburt** [comment]
I don't mind. I agree.

**Comment by bobthecow** [comment]
Done!

**Pull request merged**
